language: cpp
script: make unit
dist: trusty

before_install:
  - eval "${MATRIX_EVAL}"

env:
  global:
    - CIBW_BUILD='cp37-* cp27-*'
    - CIBW_TEST_REQUIRES='pytest'
    - CIBW_BEFORE_BUILD='pip install "numpy>=1.16" && pip install "pandas>=0.24" && pip install "pytest>=4.3" && pip install "cmake==3.13.3" && pip install "pybind11>=2.4"'
    - CIBW_TEST_COMMAND='python -m pytest {project}/tests'


matrix:
  include:

    - os: linux
      if: tag != master-builds
      dist: bionic
      name: GCC 9
      python: 3.7

     
      install:
        - eval "${MATRIX_EVAL}"

      script:
        - mkdir -p src/amalgamation/ build/release/src/ 
        - touch src/amalgamation/duckdb.cpp src/amalgamation/duckdb.hpp build/release/src/libduckdb.so src/amalgamation/duckdb.hpp build/release/duckdb_cli

      before_deploy:
        - zip -j libduckdb-src.zip src/amalgamation/duckdb.cpp src/amalgamation/duckdb.hpp
        - zip -j libduckdb-linux-amd64.zip build/release/src/libduckdb.so src/amalgamation/duckdb.hpp
        - zip -j duckdb_cli-linux-amd64.zip build/release/duckdb_cli

      deploy:
        provider: releases
        on:
          branch: master # TODO
        tag_name: master-builds

        api_key:
          secure: w/Prf0+FS5S6VCO5YvrFRu8OTPqi3errPD8CSojoFU3JUfw47a0DX7DOWVOzDQUQNERbfPkDHLA/Lt/BaZRySoVhF9TXguLxKh/o8SbcGh7L8ZT9EeH+uYbscGe55v8ggTBoBYLJbB7xMwPmANovE1hYSci4XJdzYVL9tk0Sxn93+Gmwkai6F5OUHxYUtVVST6luKDgrZgVBaXWWBgf25yNT+SaG3DSXd43tKHVclXi3KBDbp9fDCJQtypTZVX5nbTyuMyQ8VCzp76ShKbhB1slqYyEPrxm0UVa8Qg9cF/75/3r08x918I0NaW0GXJKRvck/Z1wBm+CnblNV0j/LOjenODsh/qST81W30tE54HEzf7zcDE/yuClsUn8xhQ61mUSMqWlkYJB9GX0EDGE2Z4r608tr5Zu5CGB4ciujvKmtsk1yTF3X9+KdtwepWpHeiQX5RA2ZbW7mLlH2BRTzsSSrGT8AvmwNQ2BWkPwAjpx0sUKTJ/F3iTHZhiNrPERvk1THHA3hrHVWkTfy8osl5tYr7vLjva6hS32kX/XW8oIGg0T6Kf8jfmqHuWSjWljlt49/wB0bWrD/nQzMeewSInkqIDYf1KTv1Kejwjr3V80BYZtNwXiJN7QljnZL7C3wpW5P5VxFzOK4OjtifawymdNCro5RyPqrxEde9v3RDi0=

        file:
          - libduckdb-src.zip
          - libduckdb-linux-amd64.zip
          - duckdb_cli-linux-amd64.zip

        skip_cleanup: true

        # - provider: releases
        #   on:
        #     tags: true

        # - 


